"""remove Migration

Revision ID: 165fe2d80854
Revises: 710d2a106f09
Create Date: 2021-04-28 13:46:41.955773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '165fe2d80854'
down_revision = '710d2a106f09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upvote')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upvote',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pitch_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('upvote_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitches.id'], name='upvote_pitch_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='upvote_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='upvote_pkey'),
    sa.UniqueConstraint('id', name='upvote_id_key')
    )
    # ### end Alembic commands ###
