"""upvote3 Migration

Revision ID: 528c1a134c57
Revises: 73e42c60678a
Create Date: 2021-04-28 12:39:38.258102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '528c1a134c57'
down_revision = '73e42c60678a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('upvote_user_id_fkey', 'upvote', type_='foreignkey')
    op.drop_constraint('upvote_pitch_id_fkey', 'upvote', type_='foreignkey')
    op.create_foreign_key(None, 'upvote', 'pitches', ['pitch_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'upvote', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'upvote', type_='foreignkey')
    op.drop_constraint(None, 'upvote', type_='foreignkey')
    op.create_foreign_key('upvote_pitch_id_fkey', 'upvote', 'pitches', ['pitch_id'], ['id'])
    op.create_foreign_key('upvote_user_id_fkey', 'upvote', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
