"""id Migration

Revision ID: 710d2a106f09
Revises: d5fc7771ad6d
Create Date: 2021-04-28 12:53:44.279162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '710d2a106f09'
down_revision = 'd5fc7771ad6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'upvote', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'upvote', type_='unique')
    # ### end Alembic commands ###
