"""upvote2 Migration

Revision ID: 73e42c60678a
Revises: 896b0858ab01
Create Date: 2021-04-28 11:20:20.441537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73e42c60678a'
down_revision = '896b0858ab01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upvote', sa.Column('upvote_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upvote', 'upvote_count')
    # ### end Alembic commands ###
