"""upvote Migration

Revision ID: 896b0858ab01
Revises: a312c215137f
Create Date: 2021-04-27 22:18:44.230819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '896b0858ab01'
down_revision = 'a312c215137f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upvote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pitch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upvote')
    # ### end Alembic commands ###
