"""like2 Migration

Revision ID: 8c62808224be
Revises: d89e5e682995
Create Date: 2021-04-29 10:18:30.929409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c62808224be'
down_revision = 'd89e5e682995'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'upvotes', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'upvotes', type_='unique')
    # ### end Alembic commands ###
